DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE2NTEzNjg4LCJ1c2VySUQiOjJ9.4fypboIZ6RPpl0S3YZ54hBptf0pTmLd4bk1scK5ewyc