POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTYxMDg2MTUsInVzZXJJRCI6MH0.KytcFKLSj0Gs9XCA-CRqHE1gPPAFFuJyHB-XzvzCEoc

{
    "name": "Test event",
    "description": "Another test event",
    "location": "Another test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}