POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE2MTY4NDM0LCJ1c2VySUQiOjJ9.QuY0X6JaDKKIt5aYV-ozklGoT6EYS-7kLwuThVksdvI

{
    "name": "Test event 3",
    "description": "Another test event 3",
    "location": "Another test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}