POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE2MTA5Mjk2LCJ1c2VySUQiOjB9.n5HcoPKNSxaXvAyZE7SJgS5yYoXI0xAQoJdfuN84coY

{
    "name": "Test event 2",
    "description": "Another test event 2",
    "location": "Another test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}