DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE2MjU1NzIwLCJ1c2VySUQiOjJ9.08O_EH64ZMrDA4xUgWcXChwrtgaQY5it-VI4z4F_nVg