POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE2NTEzNDMyLCJ1c2VySUQiOjJ9.jPIIHoYKkdnsKVtPQ924A_gHSRqp74rZEIkvuC82tD0
