POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE2NDI2NjY5LCJ1c2VySUQiOjJ9.sY0-C-FDXvXXmTRCD6E_O6XpRydLsjRtFOVrTr66SmY
